### ISSUE TITLE
GRANT OR REVOKE PRIVILEGES/RIGHTS

### ISSUE THREAD

**Issue by steom** [Bill-Stewart/PrivMan#1]
ok but...
it's possible make them effective in real time? without a reboot/logoff? ;)
this would be the turning point!

**Comment by Bill-Stewart** [comment]
Windows privilege changes have the same behavior as group changes (Windows does not reflect group memberships changes when an account is logged on, either). If an account is logged on, the account must log off and back on to see privilege changes.
