### ISSUE TITLE
Unclear wording of the error when revoking the privilege again

### ISSUE THREAD

**Issue by b-user** [Bill-Stewart/PrivMan#3]
PrivMan v1.0.2

User == U (user from the "users" usergroup)

cmd - "run as admin"
PrivMan -a U -g "SeManageVolumePrivilege"
PrivMan -a U -r "SeManageVolumePrivilege"
PrivMan -a U -r "SeManageVolumePrivilege"

result:
"The system cannot find the file specified. (2)"

![Снимок экрана 2024-05-22 085458](https://github.com/Bill-Stewart/PrivMan/assets/11581901/dc3fcc38-76dc-47ab-9efc-4644b2388887)

**Comment by Bill-Stewart** [comment]
That's the error code returned from the API, and the code simply outputs the localized error message string from that error code. So: WAD (working as designed), not a bug. Error code 2 should thus be interpreted as "I couldn't find it" rather than "I couldn't find the file".
